4392 Schema Change for Notations
bcgov/business-schemas pull request #59
Opened 2021-05-07 12:11 UTC by vysakh-menon-aot

*Issue #:* /bcgov/entity#4392

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-schemas license (Apache 2.0).

2021-05-07 16:42 UTC, severinbeauvais approved these changes

2021-05-07 17:23 UTC, severinbeauvais reviewed
These changes will require Edit UI to update how it saves the filing data. What's the plan to handle this dependency? (Other ticket? Timeline for this?)

2021-05-07 17:47 UTC, thorwolpert requested changes
The changes to court-order are incorrect.
I don't believe adding in registrars notations should be done to a generic order, as this diverges from our push to align across products.

2021-05-14 18:10 UTC, thorwolpert approved these changes

2021-05-14 18:10 UTC, merged